
version: '3.8'

services:
  skeletron:
    image: flexlug/skeletron:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      # Discord authorization
      "Token": "DISCORD_SECRET"
      
      # For osu services
      "BanchoClientId": 123456
      "BanchoSecret": "BANCHO_SECRET"
      
      # Due to all info from VK links is being retrieved from official VK API
      # you have to specify VK Standalone Application Token
      "VkSecret": "VK_SECRET"