// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WAV_Bot_DSharp.Services.Entities;

namespace WAV_Bot_DSharp.Migrations
{
    [DbContext(typeof(TrackedUserContext))]
    [Migration("20210223061447_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("WAV_Bot_DSharp.Services.Structures.TrackedUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BanchoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BanchoRecentLastAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BanchoTopLastAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BanchoTrackRecent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BanchoTrackTop")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GatariId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GatariRecentLastAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GatariTopLastAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GatariTrackRecent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GatariTrackTop")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrackedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
